### ISSUE TITLE
Add Video progress bar

### ISSUE THREAD

**Issue by Lumbago1337** [CGodiksen/video-spoiler-blocker#1]
I really like your add-on, since it allows specifying one channel.
As a new feature I would suggest adding to hide the progress bar of the Youtube video.
Similar to other add-ons, who can already do that, but have no filter function: 
https://addons.mozilla.org/de/firefox/addon/timeless-video/
https://addons.mozilla.org/de/firefox/addon/youtube-no-spoilers/
https://addons.mozilla.org/de/firefox/addon/youtube-antispoiler/

**Comment by CGodiksen** [comment]
Thank you very much for the feature request. I definitely see why hiding the progress bar would be useful so i have released a new version of the extension that makes it possible to toggle the progress bar and the current time. I hope this helps.
